### ISSUE TITLE
slashdot.org blocked

### ISSUE THREAD

**Issue by thomasd3** [ryanbr/fanboy-adblock#1385]
In the annoyance list:

`slashdot.org`

is blocked. I see a few entries blocking various elements, which is good, but there is also an entry with the domain itself.

I am using the list with NextDNS, so it is blocked at the DNS level.

**Comment by krystian3w** [comment]
see https://github.com/ryanbr/fanboy-adblock/issues/1386 https://github.com/nextdns/metadata/issues/368

this is should fixed by @nextDNS, not by `ryanbr`.

https://github.com/ryanbr/fanboy-adblock/blob/d5560704d6227e284c0ffb441645f720da592658/fanboy-addon/fanboy-addon-thirdparty.txt#L168

`^$third-party` is property for adblocker, but bad converted in NextDNS.

**Comment by krystian3w** [comment]
I can not found domain in file https://www.fanboy.co.nz/enhancedstats.txt, maybe @nextdns use outdated file.

**Comment by thomasd3** [comment]
I have written their support and gave them the link to this thread, so we will see what they reply. I don't know how often then update the file

**Comment by ryanbr** [comment]
Closing, no longer applicable
