### ISSUE TITLE
Merge easylist pt-br with fanboy's spanish/portuguese list

### ISSUE THREAD

**Issue by Felipefpl** [ryanbr/fanboy-adblock#289]
I noticed that spanish/portuguese list contains a few brazilians ads but not the ones that are inside this list:

https://raw.githubusercontent.com/rbrito/easylist-ptbr/master/adblock-rules.txt

A merge would be a good idea, specially because this list hasnt been updated for a long time, even so it contains a lot of stuff.

**Comment by SMed79** [comment]
1. Filter lists authors will not add rules without a proof and without checking them self the ads.
2. The **easylist-ptbr** filter list is outdated and abandoned since 5 years ago.

**Comment by Felipefpl** [comment]
1. i understand but the proof is inside the easylist's file.
2. yes, it's abandoned but it works, i have it here plus the spanish/portuguese list doesnt contain 5% of all things listed there. ;)

**Comment by Felipefpl** [comment]
1. i understand but the proof is inside the easylist's file.
2. yes, it's abandoned but it works, i have it here plus the spanish/portuguese list doesnt contain 5% of all brazilian ads listed there. ;)

**Comment by SMed79** [comment]
If you are familiar with **adblock plus** [filter syntax](https://adblockplus.org/filters), you can creat a **portuguese filter list** and displayed it on [Known Adblock Plus subscriptions page](https://adblockplus.org/en/subscriptions) so that all portuguese users will benefit.

Here a template example: https://pastebin.com/raw/gDU2LEap

help: https://forums.lanik.us/viewtopic.php?f=23&t=39884

**Comment by ryanbr** [comment]
I'm fine if another subscription author merges any changes from the regional lists, but I'm not going to initiate this.
