### ISSUE TITLE
portalcineindio.com [Breakage] [FETL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#641]
### List the website(s) you're having issues:

`https://portalcineindio.com/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Enhanced Tracking List
enabling regional list IDN: ABPindo doesn't fix the issue

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Enhanced Tracking List</summary>

![zrzut1](https://user-images.githubusercontent.com/43844449/48311516-4b435780-e5a1-11e8-8997-e6f00f161e69.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Enhanced Tracking List</summary>

![zrzut2](https://user-images.githubusercontent.com/43844449/48311520-4ed6de80-e5a1-11e8-8943-274ca35258ef.png)

</details>

**Comment by THEtomaso** [comment]
Summary:

### Affected site:
`https://portalcineindio.com/`

### Issue:
Modal backdrop prevents site navigation.

### Possible fix:
`/favicon.ico$image,third-party,domain=~portalcineindio.com`

### Note:
`/favicon.ico$image,third-party,domain=~portalcineindio.com` is needed for '**Fanboy's Enhanced Tracking List**', since this is the very blocking rule that is causing the overlay.
Alternatively, this rule (found in '**Fanboy's Annoyance List**' and '**Fanboy's Social Blocking List**') can be used instead (if not reserved for social filters):
`/plugins/super-socializer/*`

**Comment by kulfoon** [comment]
The both fixes are working.

**Comment by ryanbr** [comment]
Works fine in Firefox/UBO

**Comment by kulfoon** [comment]
Not really, the issue is still here, but it won't fix anyway because it's the favicon thing again as per https://github.com/ryanbr/fanboy-adblock/issues/688#issuecomment-441432194.
