### ISSUE TITLE
tillystoreline.com [Breakage] [FETL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#642]
### List the website(s) you're having issues:

`https://tillystoreline.com/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Enhanced Tracking List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Enhanced Tracking List</summary>

![zrzut1](https://user-images.githubusercontent.com/43844449/48311572-f5bb7a80-e5a1-11e8-8377-9659c55e1783.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Enhanced Tracking List</summary>

![zrzut2](https://user-images.githubusercontent.com/43844449/48311575-f94f0180-e5a1-11e8-8870-3936b82746f4.png)

</details>

**Comment by THEtomaso** [comment]
Summary:

### Affected site:
`https://tillystoreline.com/`

### Issue:
Modal backdrop prevents site navigation.

### Possible fix:
```
tillystoreline.com###heateor_ss_browser_popup_bg
/favicon.ico$image,third-party,domain=~tillystoreline.com
```

### Note:
`/favicon.ico$image,third-party,domain=~tillystoreline.com` is needed for '**Fanboy's Enhanced Tracking List**', since this blocking rule is partially responsible for causing the overlay.
Alternatively, this rule (found in '**Fanboy's Annoyance List**' and '**Fanboy's Social Blocking List**') can be used instead (if not reserved for social filters):
`/plugins/super-socializer/*`

**Comment by ryanbr** [comment]
Browsed the site, works fine in Firefox/UBO.
