### ISSUE TITLE
uniters.org [Breakage] [FETL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#643]
### List the website(s) you're having issues:

`https://uniters.org/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Enhanced Tracking List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Enhanced Tracking List</summary>

![ss_002](https://user-images.githubusercontent.com/43844449/48311643-22bc5d00-e5a3-11e8-9976-10db6aa94bf5.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Enhanced Tracking List</summary>

![ss_003](https://user-images.githubusercontent.com/43844449/48311644-27811100-e5a3-11e8-962e-746a1884805f.png)

</details>

**Comment by THEtomaso** [comment]
Summary:

### Affected site:
`https://uniters.org/`

### Issue:
Modal backdrop prevents site navigation.

### Possible fix:
```
uniters.org###heateor_ss_browser_popup_bg
/favicon.ico$image,third-party,domain=~uniters.org
```

### Note:
`/favicon.ico$image,third-party,domain=~uniters.org` is needed for '**Fanboy's Enhanced Tracking List**', since this blocking rule is partially responsible for causing the overlay.
Alternatively, this rule (found in '**Fanboy's Annoyance List**' and '**Fanboy's Social Blocking List**') can be used instead (if not reserved for social filters):
`/plugins/super-socializer/*`

**Comment by ryanbr** [comment]
Tested in Firefox/UBO, works fine.

**Comment by kulfoon** [comment]
Not really, the issue is still here, but it won't fix anyway because it's the favicon thing again as per https://github.com/ryanbr/fanboy-adblock/issues/688#issuecomment-441432194.
