### ISSUE TITLE
zistaz.com [Breakage] [FETL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#644]
### List the website(s) you're having issues:

`https://zistaz.com/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Enhanced Tracking List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Enhanced Tracking List</summary>

![ss_004](https://user-images.githubusercontent.com/43844449/48311673-a37b5900-e5a3-11e8-9402-b326ce9206cd.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Enhanced Tracking List</summary>

![ss_005](https://user-images.githubusercontent.com/43844449/48311674-a70ee000-e5a3-11e8-853e-8c24e299703d.png)

</details>

**Comment by THEtomaso** [comment]
Summary:

### Affected site:
`https://zistaz.com/`

### Issue:
Modal backdrop prevents site navigation.

### Possible fix:
`/favicon.ico$image,third-party,domain=~zistaz.com`

### Note:
`/favicon.ico$image,third-party,domain=~zistaz.com` is needed for '**Fanboy's Enhanced Tracking List**', since this is the very blocking rule that is causing the overlay.
Alternatively, this rule (found in '**Fanboy's Annoyance List**' and '**Fanboy's Social Blocking List**') can be used instead (if not reserved for social filters):
`/plugins/super-socializer/*`

**Comment by ryanbr** [comment]
Tested in Firefox, UBo. works fine.
