### ISSUE TITLE
auswandern.uy [Breakage] [FETL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#645]
### List the website(s) you're having issues:

`http://www.auswandern.uy/`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Enhanced Tracking List
enabling regional list DEU: EasyList Germany doesn't fix the issue

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Enhanced Tracking List</summary>

![ss_007](https://user-images.githubusercontent.com/43844449/48311713-374d2500-e5a4-11e8-971d-14e37fce0cdc.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling Fanboy’s Enhanced Tracking List</summary>

![ss_006](https://user-images.githubusercontent.com/43844449/48311711-32887100-e5a4-11e8-850e-7e3677d50206.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after accepting the message</summary>

![ss_008](https://user-images.githubusercontent.com/43844449/48311716-61064c00-e5a4-11e8-8314-82e8b6c4bc20.png)

</details>

**Comment by THEtomaso** [comment]
Summary:

### Affected site:
`http://www.auswandern.uy/`

### Issue:
Modal backdrop prevents site navigation.

### Possible fix:
`/favicon.ico$image,third-party,domain=~auswandern.uy`

### Note:
* `/favicon.ico$image,third-party,domain=~auswandern.uy` is needed for '**Fanboy's Enhanced Tracking List**', since this is the very blocking rule that is causing the overlay.
Alternatively, this rule (found in '**Fanboy's Annoyance List**' and '**Fanboy's Social Blocking List**') can be used instead (if not reserved for social filters):
`/plugins/super-socializer/*`

**Comment by ryanbr** [comment]
Works fine with Firefox/UBO.

**Comment by kulfoon** [comment]
Not really, the issue is still here, but it won't fix anyway because it's the favicon thing again as per https://github.com/ryanbr/fanboy-adblock/issues/688#issuecomment-441432194.
