### ISSUE TITLE
gayecho.com [Breakage] [FETL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#647]
### List the website(s) you're having issues:

`http://gayecho.com/`

### What happens?

Breakage - the page won't load - shadow overlay (after closing anti-adblock message).

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Enhanced Tracking List
enabling regional lists:
HUN: hufilter
ROU: Romanian Ad (ROad) Block List Light​
doesn't fix the issue

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - the anti-adblock message with or without enabling Fanboy’s Enhanced Tracking List</summary>

![ss_016](https://user-images.githubusercontent.com/43844449/48311962-f525e280-e5a7-11e8-98dd-d709997b1da7.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after enabling Fanboy’s Enhanced Tracking List + after accepting the anti-adblock message</summary>

![ss_015](https://user-images.githubusercontent.com/43844449/48311967-feaf4a80-e5a7-11e8-8dbf-d688e5cca918.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after disabling Fanboy’s Enhanced Tracking List + after accepting the anti-adblock message</summary>

![ss_014](https://user-images.githubusercontent.com/43844449/48311972-1a1a5580-e5a8-11e8-8ed4-ad05ef8ed926.png)

</details>

**Comment by THEtomaso** [comment]
Summary:

### Affected site:
`http://gayecho.com/`

### Issues:
* Anti-adblock message
* Shadow overlay

### Possible fix:
```
@@||gayecho.com^$generichide
/favicon.ico$image,third-party,domain=~gayecho.com
```

### Note:
`/favicon.ico$image,third-party,domain=~gayecho.com` is needed for '**Fanboy's Enhanced Tracking List**', since this is the very blocking rule that is causing the overlay.
Alternatively, this rule (found in '**Fanboy's Annoyance List**' and '**Fanboy's Social Blocking List**')  can be used instead (if not reserved for social filters):
`/plugins/super-socializer/*`
