### ISSUE TITLE
terradrift.com [Breakage] [FETL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#648]
### List the website(s) you're having issues:

`https://terradrift.com/`

### What happens?

Breakage - the page won't load - shadow overlay (after closing anti-adblock message).

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Enhanced Tracking List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - the anti-adblock message with or without enabling Fanboy’s Enhanced Tracking List</summary>

![ss_018](https://user-images.githubusercontent.com/43844449/48312030-1804c680-e5a9-11e8-879d-44386495e76d.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after enabling Fanboy’s Enhanced Tracking List + after accepting the anti-adblock message</summary>

![ss_020](https://user-images.githubusercontent.com/43844449/48312034-1fc46b00-e5a9-11e8-9042-4a6ad4f6e2bd.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after disabling Fanboy’s Enhanced Tracking List + after accepting the anti-adblock message</summary>

![ss_019](https://user-images.githubusercontent.com/43844449/48312036-25ba4c00-e5a9-11e8-8834-8f54a1df1a22.png)

</details>

**Comment by kulfoon** [comment]
Most probably you are aware of it already like most of experienced people, but just for make sure, do you clear both browser's cookies & cache before trying to reproduce the shadow overlay issues? As they can be reproduced in most cases only the first fresh time you visit website.

Also to provide more info abut the overlay shadow I've made a screenshoot with uBO element picker:

<details not-open>
<summary>terradrift.com shadow overlay screenshoot</summary>

![ss_034](https://user-images.githubusercontent.com/43844449/48312557-f0196100-e5b0-11e8-994f-017e393ad154.png)

</details>

**Comment by THEtomaso** [comment]
> do you clear both browser's cookies & cache before trying to reproduce the shadow overlay issues?

Yes, of course.
I also tried to disable a bunch of filters, which you're not using.
And I looked in uBO's logger to see if I could find it there.

**Comment by kulfoon** [comment]
I've updated my comment above with uBO logger screenshoots, can they help to solve the issue? If not what can I else do to help?

**Comment by THEtomaso** [comment]
I'm connecting from Norway.
I also tried to connect from Germany, Netherlands and USA, using the free proxies here:
`https://hide.me/en/proxy/`
Still no overlays.

How about from your end?
Does the overlays disappear when you connect through those proxies?

**Comment by kulfoon** [comment]
I've tried Browsec `https://browsec.com/en/` as an browser extension:
`https://chrome.google.com/webstore/detail/browsec-vpn-free-and-unli/omghfjlpggmjjaagoclmmobgdodcjboh`
`https://addons.mozilla.org/pl/firefox/addon/browsec/`

<details not-open>
<summary>Browsec screenshoot</summary>

![ss_039](https://user-images.githubusercontent.com/43844449/48312754-e34a3c80-e5b3-11e8-8a8d-86aa9e07101b.png)

</details>
.

with all 4 free vpn proxies (Netherlands, Singapore, United Kingdom, United States) and still can reproduce on all of them!

**Comment by kulfoon** [comment]
Nothing, still no change, can you tell me what filter does block the shadow overlay for you? As seen from the uBO element picker screenshoot as per https://github.com/ryanbr/fanboy-adblock/issues/648#issuecomment-437664200 it says that the overlay shadow is either:
`||terradrift.com/wp-content/plugins/super-socializer/images/transparent_bg.png` or
`###heateor_ss_browser_popup_bg`

Or maybe for you it isn't even blocked by any filter because there is no overlay shadow at all for you?

**Comment by THEtomaso** [comment]
OK, I think that I might have found the problem now..
Like I pointed out in one of my earlier posts; `terradrift.com` is affected by a timing issue, described by gorhill.
At my end, I didn't see the overlays, because '**Fanboy's Annoyance List**' and '**Fanboy's Social Blocking List**' blocked it, with the following rule:
`/plugins/super-socializer/*`
..but at your end, the timing issue probably renders the generic rule useless (although, I thought it only affected cosmetic filters).

So, what happens if you make that rule site-specific, like this?:
`/plugins/super-socializer/*$domain=terradrift.com`
Does this fix the problem at your end?

**Comment by kulfoon** [comment]
> THEtomaso : At my end, I didn't see the overlays, because **'Fanboy's Annoyance List'** and **'Fanboy's Social Blocking List'** blocked it, with the following rule:
> /plugins/super-socializer/*

As you can see the title of the issue is: 

> terradrift.com [Breakage] [FETL]

FETL = Fanboy's Enhanced Tracking List

And the content of the 1st comment also mentions only  Fanboy's Enhanced Tracking List.

I nowhere have mentioned about other Fanboy's lists...

I don't have the shadow overlay if 'Fanboy's Annoyance List' or 'Fanboy's Social Blocking List' enabled.

So it seems that you've made a mistake by trying to reproduce the issue with wrong filter lists enabled.

**Comment by THEtomaso** [comment]
Indeed.
I read your first post too fast, and assumed that you were using '**Fanboy's Annoyance List**' and '**Fanboy's Social Blocking List**'.
Those were the filters that I tested it against. :)

**Comment by THEtomaso** [comment]
Summary (so ryanbr won't have to read through everyting):

### Affected site:
`https://terradrift.com/`

### Issues:
* Anti-adblock message
* Shadow overlay
* Nag message (about blocked features)

### Possible fix:
```
@@||terradrift.com^$generichide
/plugins/super-socializer/*
terradrift.com###the_champ_sharing_more_providers
```

### Notes:
* `/plugins/super-socializer/*` is needed for '**Fanboy's Enhanced Tracking List**', since the overlay is triggered by the following blocking rule:
`/favicon.ico$image,third-party`

* `terradrift.com###the_champ_sharing_more_providers` is needed for '**Fanboy's Enhanced Tracking List**', since the existing generic rule doesn't work for all browsers.
This is because of a rare timing issue, explained by gorhill here:
https://github.com/gorhill/uBlock/issues/1885#issuecomment-238595017
