### ISSUE TITLE
dollardestruction.com [Breakage] [FETL]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#651]
### List the website(s) you're having issues:

`https://dollardestruction.com`

### What happens?

Breakage - the page won't load - shadow overlay

### List Subscriptions you're using:

uBO default +
uBO annoyance +
Fanboy’s Enhanced Tracking List

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit /  Opera 56 64bit
- Adblock Extension/version: uBlock Origin version: 1.17.2

### Other details:

Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Enhanced Tracking List</summary>

![ss_027](https://user-images.githubusercontent.com/43844449/48312327-77fd6c00-e5ad-11e8-905e-3fc9e9e0d871.png)

</details>
.

</details>

<details not-open>
<summary>screenshoot 2 - after enabling Fanboy’s Enhanced Tracking List + accepting the cookie message (it seems to skip the shadow overlay there should be the newsletter message [as on the screenshoots 3 and 4, but it's missing, and the cookie message has no shadow overlay so clicking it actually won't hide the shadow overlay)</summary>

![ss_028](https://user-images.githubusercontent.com/43844449/48312332-8b103c00-e5ad-11e8-8c45-a1a08c2f44c2.png)

</details>
.

<details not-open>
<summary>screenshoot 3 - after disabling Fanboy’s Enhanced Tracking List</summary>

![ss_029](https://user-images.githubusercontent.com/43844449/48312356-99f6ee80-e5ad-11e8-9144-f95a604d41e1.png)

</details>
.

<details not-open>
<summary>screenshoot 4 - after disabling Fanboy’s Enhanced Tracking List + after accepting the newsletter message</summary>

![ss_030](https://user-images.githubusercontent.com/43844449/48312358-a418ed00-e5ad-11e8-8838-f990c4dd4288.png)

</details>

**Comment by THEtomaso** [comment]
`@@||loginissue.help^$generichide`

**Comment by THEtomaso** [comment]
Summary:

### Affected site:
https://dollardestruction.com/

### Issue:
Newsletter popup and modal backdrop prevents site navigation.

### Possible fix:
```
dollardestruction.com##.mailmunch-popover
dollardestruction.com##.mailmunch-popover-content
/favicon.ico$image,third-party,domain=~dollardestruction.com
```

Note:
`/favicon.ico$image,third-party,domain=~dollardestruction.com` is needed for '**Fanboy's Enhanced Tracking List**', since this blocking rule is partially responsible for causing the overlay.
Alternatively, this rule (found in '**Fanboy's Annoyance List**' and '**Fanboy's Social Blocking List**') can be used instead (if not reserved for social filters):
`/plugins/super-socializer/*`
