### ISSUE TITLE
humo.be [Cookie Wall]

### ISSUE THREAD

**Issue by kulfoon** [ryanbr/fanboy-adblock#656]
### List the website(s) you're having issues:

`https://www.humo.be/`

### What happens?

Cookie wall appears (breaks scroll if hidden)

### List Subscriptions you're using:

uBO default + Fanboy's Cookiemonster List

Other list also don't fix the issue:
I don't care about cookies
Prebake - Filter Obtrusive Cookie Notices​
I'm OK with cookies

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- Adblock Extension/version: uBO 1.17.2

### Other details:

<details not-open>
<summary>Screenshoot 1:</summary>

![ss_016](https://user-images.githubusercontent.com/43844449/48342828-0ab30f00-e671-11e8-88ea-907c9761bfe7.png)

</details>

**Comment by THEtomaso** [comment]
@kulfoon:

Video playback on this site is already broken, because of the following filters:
* AdGuard Spyware filter
* EasyPrivacy
* MVPS HOSTS

..so you might want to file some additional reports.

Example:
`https://www.humo.be/actua/395877/`

Problem rule:
`||analytics.ooyala.com^`

Possible fix:
`@@||analytics.ooyala.com^$domain=humo.be`

**Comment by ryanbr** [comment]
Can't be fixed, (cookie)
