### ISSUE TITLE
Fanboy’s Enhanced Tracking List breaks favicons in tabs in Firefox

### ISSUE THREAD

**Issue by GoodGuyNick** [ryanbr/fanboy-adblock#667]
### List the website(s) you're having issues:

Issue affects many websites. Examples:
`https://askubuntu.com`, `https://unix.stackexchange.com`

### What happens?

When you load a page there is no favicon in tab. On some there is but on the others there are non.

### List Subscriptions you're using:

Fanboy’s Enhanced Tracking List
### Your settings

- OS/version: Ubuntu 18.04.1
- Browser/version: Firefox 63.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin

**Comment by THEtomaso** [comment]
This is by design, and it happen because of the following rule:
`/favicon.ico$image,third-party`

The sites that you refer to pulls their favicons from this third-party domain:
`cdn.sstatic.net`

The reasoning behind blocking favicons:
```
https://stackoverflow.com/questions/16828763/
https://en.wikipedia.org/wiki/Favicon#Limitations_and_criticism
```

Unfortunately, as you can see from several reports posted kulfoon this week, favicons blocking can also lead to breakage!

**Comment by smed79** [comment]
Example of using favicon for tracking.

```
https://stackoverflow.com/questions/16828763/use-favicon-to-track-user-visit-to-a-website
```

**Comment by THEtomaso** [comment]
It's the same link that I posted. :)

**Comment by dikiaap** [comment]
@ryanbr GitHub also moves the favicon to https://github.githubassets.com/favicon.ico
